/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.currencyconverter;

import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ju
 */
public class CurrencyConverter extends javax.swing.JFrame {

    private enum Currency{
        EUR, USD;        
    }
    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter() {
        initComponents();
        ImageIcon arrow = new ImageIcon("src/main/java/es/ulpgc/images/flecha.png");
        Icon arrowIcon = new ImageIcon(arrow.getImage().getScaledInstance(arrowImage.getWidth(), arrowImage.getHeight(), Image.SCALE_SMOOTH));
        arrowImage.setIcon(arrowIcon);

        ImageIcon money = new ImageIcon("src/main/java/es/ulpgc/images/dinero.png");
        Icon moneyIcon = new ImageIcon(money.getImage().getScaledInstance(moneyImage.getWidth(), moneyImage.getHeight(), Image.SCALE_SMOOTH));
        moneyImage.setIcon(moneyIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        globalPanel = new javax.swing.JPanel();
        resetPanel = new javax.swing.JPanel();
        finalAmount = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        member1 = new javax.swing.JLabel();
        member2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        moneyImage = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        currencyPanel = new javax.swing.JPanel();
        initialCurrency = new javax.swing.JTextField();
        arrowImage = new javax.swing.JLabel();
        finalCurrency = new javax.swing.JTextField();
        orangeLine2 = new javax.swing.JPanel();
        orangeLine1 = new javax.swing.JPanel();
        amountPanel = new javax.swing.JPanel();
        amount = new javax.swing.JTextField();
        convertPanel = new javax.swing.JPanel();
        orangeLine3 = new javax.swing.JPanel();
        convert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        globalPanel.setBackground(new java.awt.Color(255, 255, 255));

        resetPanel.setBackground(new java.awt.Color(255, 255, 255));

        finalAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalAmount.setText("0.00");
        finalAmount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        finalAmount.setPreferredSize(new java.awt.Dimension(232, 47));
        finalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalAmountActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 255, 255));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        member1.setText("Cristina Falcón Carqué");

        member2.setText("Gabriel Boullosa Rodríguez");

        jLabel1.setText("Authors:");

        javax.swing.GroupLayout resetPanelLayout = new javax.swing.GroupLayout(resetPanel);
        resetPanel.setLayout(resetPanelLayout);
        resetPanelLayout.setHorizontalGroup(
            resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(finalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(resetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resetPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(78, 78, 78)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(member1)
                    .addComponent(member2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resetPanelLayout.setVerticalGroup(
            resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resetPanelLayout.createSequentialGroup()
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(member1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(member2)
                .addContainerGap())
        );

        titlePanel.setBackground(new java.awt.Color(255, 153, 0));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Currency Converter");
        Title.setPreferredSize(new java.awt.Dimension(207, 59));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(moneyImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addComponent(moneyImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        currencyPanel.setBackground(new java.awt.Color(255, 255, 255));

        initialCurrency.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        initialCurrency.setForeground(new java.awt.Color(204, 204, 204));
        initialCurrency.setText("USD/EUR");
        initialCurrency.setBorder(null);
        initialCurrency.setPreferredSize(new java.awt.Dimension(84, 25));
        initialCurrency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                initialCurrencyMouseClicked(evt);
            }
        });
        initialCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialCurrencyActionPerformed(evt);
            }
        });

        arrowImage.setBackground(new java.awt.Color(255, 255, 255));

        finalCurrency.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalCurrency.setForeground(new java.awt.Color(204, 204, 204));
        finalCurrency.setText("EUR/USD");
        finalCurrency.setBorder(null);
        finalCurrency.setPreferredSize(new java.awt.Dimension(84, 25));
        finalCurrency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finalCurrencyMouseClicked(evt);
            }
        });
        finalCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalCurrencyActionPerformed(evt);
            }
        });

        orangeLine2.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout orangeLine2Layout = new javax.swing.GroupLayout(orangeLine2);
        orangeLine2.setLayout(orangeLine2Layout);
        orangeLine2Layout.setHorizontalGroup(
            orangeLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        orangeLine2Layout.setVerticalGroup(
            orangeLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        orangeLine1.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout orangeLine1Layout = new javax.swing.GroupLayout(orangeLine1);
        orangeLine1.setLayout(orangeLine1Layout);
        orangeLine1Layout.setHorizontalGroup(
            orangeLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        orangeLine1Layout.setVerticalGroup(
            orangeLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout currencyPanelLayout = new javax.swing.GroupLayout(currencyPanel);
        currencyPanel.setLayout(currencyPanelLayout);
        currencyPanelLayout.setHorizontalGroup(
            currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currencyPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(initialCurrency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangeLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrowImage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(finalCurrency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangeLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        currencyPanelLayout.setVerticalGroup(
            currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currencyPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arrowImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(currencyPanelLayout.createSequentialGroup()
                        .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(initialCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(currencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orangeLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orangeLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        amountPanel.setBackground(new java.awt.Color(255, 255, 255));

        amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        amount.setForeground(new java.awt.Color(204, 204, 204));
        amount.setText("AMOUNT: 0.00");
        amount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        amount.setPreferredSize(new java.awt.Dimension(232, 47));
        amount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amountMouseClicked(evt);
            }
        });
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        amountPanel.add(amount);

        convertPanel.setBackground(new java.awt.Color(255, 255, 255));

        orangeLine3.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout orangeLine3Layout = new javax.swing.GroupLayout(orangeLine3);
        orangeLine3.setLayout(orangeLine3Layout);
        orangeLine3Layout.setHorizontalGroup(
            orangeLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        orangeLine3Layout.setVerticalGroup(
            orangeLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        convert.setBackground(new java.awt.Color(255, 255, 255));
        convert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        convert.setText("CONVERT");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout convertPanelLayout = new javax.swing.GroupLayout(convertPanel);
        convertPanel.setLayout(convertPanelLayout);
        convertPanelLayout.setHorizontalGroup(
            convertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convertPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(orangeLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        convertPanelLayout.setVerticalGroup(
            convertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, convertPanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(convertPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(orangeLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout globalPanelLayout = new javax.swing.GroupLayout(globalPanel);
        globalPanel.setLayout(globalPanelLayout);
        globalPanelLayout.setHorizontalGroup(
            globalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(currencyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(amountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(convertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(resetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        globalPanelLayout.setVerticalGroup(
            globalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(globalPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currencyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(globalPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialCurrencyActionPerformed

    private void finalCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalCurrencyActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        amount.setText("");
    }//GEN-LAST:event_amountActionPerformed

    private void finalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalAmountActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        
        String from = initialCurrency.getText().toUpperCase();
        String to = finalCurrency.getText().toUpperCase();
        
        if(from.equals("EUR")){
            finalCurrency.setForeground(Color.BLACK);
            finalCurrency.setText("USD");
        }else if(from.equals("USD")){
            finalCurrency.setForeground(Color.BLACK);
            finalCurrency.setText("EUR");
        }else{
            JOptionPane.showMessageDialog(null, "Insert USD or EUR", "Currency not valid", JOptionPane.WARNING_MESSAGE);
        }
        
        
        double total = 0;
        try {                                         
            double amountMoney = Double.parseDouble(amount.getText().replace(',', '.'));
            amountMoney = (double)Math.round(amountMoney * 100d) / 100d;
            URL url = new URL("https://free.currconv.com/api/v7/convert?q=" + from + "_" + to + "&compact=ultra&apiKey=17826d13349ad85c81fd");
            URLConnection connection = url.openConnection();
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
                String line =  reader.readLine();
                String line1 = line.substring(line.indexOf(":")+1,line.indexOf("}"));
                
                total = Double.parseDouble(line1) * amountMoney;
                total = (double)Math.round(total * 100d) / 100d;
                
                finalAmount.setText("");
                DecimalFormat formato = new DecimalFormat("#.00");
                finalAmount.setText(String.valueOf(formato.format(total)).replace(',', '.'));
            } catch (IOException ex) {
                Logger.getLogger(CurrencyConverter.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(CurrencyConverter.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CurrencyConverter.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Only numbers allowed", "Amount not valid", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_convertActionPerformed

        
    
    private void amountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amountMouseClicked
        if(amount.getText().equals("AMOUNT: 0.00")){
            amount.setText("");
            amount.setForeground(Color.black);
        }
    }//GEN-LAST:event_amountMouseClicked

    private void initialCurrencyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initialCurrencyMouseClicked
        if(initialCurrency.getText().equals("USD/EUR")){
            initialCurrency.setText("");
            initialCurrency.setForeground(Color.black);
        }
    }//GEN-LAST:event_initialCurrencyMouseClicked

    private void finalCurrencyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalCurrencyMouseClicked
        if(finalCurrency.getText().equals("EUR/USD")){
            finalCurrency.setText("");
            finalCurrency.setForeground(Color.black);
        }
    }//GEN-LAST:event_finalCurrencyMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        initialCurrency.setForeground(new java.awt.Color(204, 204, 204));
        amount.setForeground(new java.awt.Color(204, 204, 204));
        finalCurrency.setForeground(new java.awt.Color(204, 204, 204));
        initialCurrency.setText("USD/EUR");
        amount.setText("AMOUNT: 0.00");
        finalCurrency.setText("EUR/USD");
        finalAmount.setText("0.00");
        
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JTextField amount;
    private javax.swing.JPanel amountPanel;
    private javax.swing.JLabel arrowImage;
    private javax.swing.JButton convert;
    private javax.swing.JPanel convertPanel;
    private javax.swing.JPanel currencyPanel;
    private javax.swing.JTextField finalAmount;
    private javax.swing.JTextField finalCurrency;
    private javax.swing.JPanel globalPanel;
    private javax.swing.JTextField initialCurrency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel member1;
    private javax.swing.JLabel member2;
    private javax.swing.JLabel moneyImage;
    private javax.swing.JPanel orangeLine1;
    private javax.swing.JPanel orangeLine2;
    private javax.swing.JPanel orangeLine3;
    private javax.swing.JButton reset;
    private javax.swing.JPanel resetPanel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
